//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Earth.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.LostPasswordRequest = new HashSet<LostPasswordRequest>();
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public int IdCampus { get; set; }
        public int IdPromotion { get; set; }
        public int Role { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PersonalEmail { get; set; }
        public string EPSIEmail { get; set; }
        public string PhoneNumber { get; set; }
        public string CityFrom { get; set; }
        public string Website { get; set; }
        public string FacebookUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string LinkedInUrl { get; set; }
        public string ViadeoUrl { get; set; }
        public string Status { get; set; }
        public string Presentation { get; set; }
        public string ImageUrl { get; set; }
        public string Url { get; set; }
        public bool Active { get; set; }
        public string GitHubUrl { get; set; }
    
        public virtual ICollection<LostPasswordRequest> LostPasswordRequest { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual Campus Campus { get; set; }
    }
}
