//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Earth.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public int IdAuthor { get; set; }
        public string Title { get; set; }
        public string ShortText { get; set; }
        public string Text { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ImageUrl { get; set; }
        public string Keywords { get; set; }
        public bool IsPublished { get; set; }
        public string Url { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
