//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Earth.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public int IdCampus { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Progression { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Campus Campus { get; set; }
    }
}
