//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Earth.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public Promotion()
        {
            this.Member = new HashSet<Member>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int GraduationYear { get; set; }
        public bool StillPresent { get; set; }
    
        public virtual ICollection<Member> Member { get; set; }
    }
}
