//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSILab.SolarSystem.Earth.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SunEntities : DbContext
    {
        public SunEntities()
            : base("name=SunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Conference> Conference { get; set; }
        public DbSet<Link> Link { get; set; }
        public DbSet<LostPasswordRequest> LostPasswordRequest { get; set; }
        public DbSet<Member> Member { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Project> Project { get; set; }
        public DbSet<Promotion> Promotion { get; set; }
        public DbSet<Show> Show { get; set; }
        public DbSet<Slide> Slide { get; set; }
        public DbSet<Campus> Campus { get; set; }
    }
}
