//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystem.Earth.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarSystem.Earth.DataAccess.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas l&apos;autorisation pour effectuer cette action. (Login: {0}).
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La publicité ne possède pas de titre..
        /// </summary>
        internal static string Advertising_NoName {
            get {
                return ResourceManager.GetString("Advertising_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La publicité ne possède pas d&apos;image..
        /// </summary>
        internal static string Advertising_NoPicture {
            get {
                return ResourceManager.GetString("Advertising_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La publicité ne contient pas de texte de présentation..
        /// </summary>
        internal static string Advertising_NoPresentation {
            get {
                return ResourceManager.GetString("Advertising_NoPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ville ne possède aucun libellé..
        /// </summary>
        internal static string City_NoName {
            get {
                return ResourceManager.GetString("City_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence n&apos;est pas associée à un campus..
        /// </summary>
        internal static string Conference_NoCity {
            get {
                return ResourceManager.GetString("Conference_NoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence ne possède pas de description..
        /// </summary>
        internal static string Conference_NoDescription {
            get {
                return ResourceManager.GetString("Conference_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence ne possède pas de nom..
        /// </summary>
        internal static string Conference_NoName {
            get {
                return ResourceManager.GetString("Conference_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conférence ne possède pas d&apos;image..
        /// </summary>
        internal static string Conference_NoPicture {
            get {
                return ResourceManager.GetString("Conference_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lieu de la conférence n&apos;est pas précisé.
        /// </summary>
        internal static string Conference_NoPlace {
            get {
                return ResourceManager.GetString("Conference_NoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le permalien de la conférence n&apos;est pas précisé..
        /// </summary>
        internal static string Conference_NoURL {
            get {
                return ResourceManager.GetString("Conference_NoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien ne possède pas de description..
        /// </summary>
        internal static string Link_NoDescription {
            get {
                return ResourceManager.GetString("Link_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien ne possède de titre..
        /// </summary>
        internal static string Link_NoName {
            get {
                return ResourceManager.GetString("Link_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien ne possède pas d&apos;image..
        /// </summary>
        internal static string Link_NoPicture {
            get {
                return ResourceManager.GetString("Link_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La demande de restauration du mot de passe pour cet utilisateur et cette clé est introuvable..
        /// </summary>
        internal static string LostPassword_RequestNotFound {
            get {
                return ResourceManager.GetString("LostPassword_RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez dépassé les 2 jours pour pouvoir redéfinir votre mot de passe. Veuillez formuler une nouvelle demande..
        /// </summary>
        internal static string LostPassword_TimeExpired {
            get {
                return ResourceManager.GetString("LostPassword_TimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce membre n&apos;est pas associé à une ville..
        /// </summary>
        internal static string Member_NoCitySelected {
            get {
                return ResourceManager.GetString("Member_NoCitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prénom du membre n&apos;est pas précisé..
        /// </summary>
        internal static string Member_NoFirstName {
            get {
                return ResourceManager.GetString("Member_NoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom du membre n&apos;est pas précisé..
        /// </summary>
        internal static string Member_NoLastName {
            get {
                return ResourceManager.GetString("Member_NoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mail EPSI n&apos;est pas renseigné..
        /// </summary>
        internal static string Member_NoMailEPSI {
            get {
                return ResourceManager.GetString("Member_NoMailEPSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe du membre n&apos;est pas précisé..
        /// </summary>
        internal static string Member_NoPassword {
            get {
                return ResourceManager.GetString("Member_NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le membre ne possède pas d&apos;image..
        /// </summary>
        internal static string Member_NoPicture {
            get {
                return ResourceManager.GetString("Member_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce membre n&apos;est pas associé à une promo..
        /// </summary>
        internal static string Member_NoPromoSelected {
            get {
                return ResourceManager.GetString("Member_NoPromoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce membre ne possède pas de rôle..
        /// </summary>
        internal static string Member_NoRoleSelected {
            get {
                return ResourceManager.GetString("Member_NoRoleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le statut du membre n&apos;est pas précisé..
        /// </summary>
        internal static string Member_NoStatus {
            get {
                return ResourceManager.GetString("Member_NoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom utilisateur et/ou le mot de passe sont incorrects..
        /// </summary>
        internal static string Member_NotFound {
            get {
                return ResourceManager.GetString("Member_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le permalien du membre n&apos;est pas précisé..
        /// </summary>
        internal static string Member_NoURL {
            get {
                return ResourceManager.GetString("Member_NoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le pseudo du membre n&apos;est pas précisé..
        /// </summary>
        internal static string Member_NoUsername {
            get {
                return ResourceManager.GetString("Member_NoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news ne possède pas d&apos;auteur..
        /// </summary>
        internal static string News_NoAuthor {
            get {
                return ResourceManager.GetString("News_NoAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news ne possède pas de texte..
        /// </summary>
        internal static string News_NoContent {
            get {
                return ResourceManager.GetString("News_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description de la news n&apos;est pas précisée..
        /// </summary>
        internal static string News_NoDescription {
            get {
                return ResourceManager.GetString("News_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news ne possède pas de mot clé pour la recherche..
        /// </summary>
        internal static string News_NoKeywords {
            get {
                return ResourceManager.GetString("News_NoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;image de la news n&apos;est pas précisé..
        /// </summary>
        internal static string News_NoPicture {
            get {
                return ResourceManager.GetString("News_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La news ne possède pas de titre..
        /// </summary>
        internal static string News_NoTitle {
            get {
                return ResourceManager.GetString("News_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le permalien de la news n&apos;est pas précisé..
        /// </summary>
        internal static string News_NoURL {
            get {
                return ResourceManager.GetString("News_NoURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;avancement du projet doit être une valeur comprise entre 0 et 100..
        /// </summary>
        internal static string Project_IncorrectProgression {
            get {
                return ResourceManager.GetString("Project_IncorrectProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet n&apos;est associé à aucun campus..
        /// </summary>
        internal static string Project_NoCitySelected {
            get {
                return ResourceManager.GetString("Project_NoCitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet ne possède pas de description..
        /// </summary>
        internal static string Project_NoDescription {
            get {
                return ResourceManager.GetString("Project_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet ne possède pas de nom..
        /// </summary>
        internal static string Project_NoName {
            get {
                return ResourceManager.GetString("Project_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet ne possède pas d&apos;image..
        /// </summary>
        internal static string Project_NoPicture {
            get {
                return ResourceManager.GetString("Project_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;année de la promo est incorrecte..
        /// </summary>
        internal static string Promo_InvalidYear {
            get {
                return ResourceManager.GetString("Promo_InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La classe ne possède pas de libellé..
        /// </summary>
        internal static string Promo_NoName {
            get {
                return ResourceManager.GetString("Promo_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description du salon n&apos;est pas précisée..
        /// </summary>
        internal static string Show_NoDescription {
            get {
                return ResourceManager.GetString("Show_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le salon ne possède de nom..
        /// </summary>
        internal static string Show_NoName {
            get {
                return ResourceManager.GetString("Show_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le salon ne possède d&apos;image..
        /// </summary>
        internal static string Show_NoPicture {
            get {
                return ResourceManager.GetString("Show_NoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lieu du salon n&apos;est pas précisé..
        /// </summary>
        internal static string Show_NoPlace {
            get {
                return ResourceManager.GetString("Show_NoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le permalien du salon n&apos;est pas précisé..
        /// </summary>
        internal static string Show_NoURL {
            get {
                return ResourceManager.GetString("Show_NoURL", resourceCulture);
            }
        }
    }
}
